language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - pypy

install:
  - pip install pytest
  - pip install pytest-flake8
  - pip install pytest-cov
  - pip install coveralls

script: py.test test.py --flake8 --cov-report= --cov=pyphen.py

after_success: coveralls

sudo: false
